### ISSUE TITLE
API Pagination

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-backend#21]
## I expect

REST API pagination to use the following request parameters:

* limit
* cursor - see https://slack.engineering/evolving-api-pagination-at-slack/

REST API Response to have the following schema

```
type: object
required:
- items
- count
- next
properties:
  count:
    type: integer
    description: number of returned entries
  next:
    type: string
    description: the next cursor URL
    example: https://onto.robertopolli.it/vocabularies/v1/vocabularies/writing-system?limit=4&cursor=ABUGIDA
  items:
    type: object
    minItems: 0
    maxItems: 100

```

## Instead

offset-based pagination

https://github.com/teamdigitale/dati-semantic-backend/blame/main/src/integration/java/it/teamdigitale/ndc/integration/RestApiIntegrationTests.java#L76
